name: secure_suite
packages:
  - packages/**

scripts:
  # This will run 'pub get' in all packages at once
  get:
    run: melos exec -- "dart pub get"

  # This will run both your generators for testing
  gen:
    run: melos exec -- "dart run secure_strings"
    run: melos exec -- "dart run secure_localizations"
  